In [1]:
import numpy as np

## Datatypes & Attributes

In [4]:
# Numpy's main datatype is ndarray (n dimentional array)
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [6]:
type(a1)

numpy.ndarray

In [8]:
a2 = np.array([[1,2.0,3.3],
             [4,5,6.5]])

a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],
              [[10,11,12],[13,14,15],[16,17,18]]])

In [9]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [10]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [11]:
a1.shape

(3,)

In [12]:
a2.shape

(2, 3)

In [13]:
a3.shape

(2, 3, 3)

In [14]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [15]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [16]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [17]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [18]:
import pandas as pd

# Creating Dataframe with Numpy Arrays
npdf = pd.DataFrame(a2)
npdf

,0,1,2
0,1.0,2.0,3.3
1,4.0,5.0,6.5


## Creating arrays

In [19]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [20]:
sample_array.dtype

dtype('int64')

In [21]:
ones = np.ones((2,3))

In [23]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
type(ones)

numpy.ndarray

In [25]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [37]:
random_array = np.random.randint(0,10,size=(3,5),dtype=int)

In [38]:
random_array

array([[7, 6, 2, 7, 5],
       [8, 7, 3, 1, 4],
       [9, 4, 7, 3, 5]])

In [39]:
random_array_2 = np.random.random((5,3))

In [40]:
random_array_2

array([[0.7588447 , 0.69617941, 0.20634269],
       [0.98742827, 0.26771638, 0.01953041],
       [0.75464938, 0.14536667, 0.57923774],
       [0.48046979, 0.68851996, 0.97563591],
       [0.49583173, 0.0226408 , 0.22600918]])

In [41]:
random_array_3 = np.random.rand(5,3)

In [42]:
random_array_3

array([[0.73207988, 0.68980172, 0.46105011],
       [0.98625156, 0.48783247, 0.15336618],
       [0.32978108, 0.09969362, 0.79846725],
       [0.13236731, 0.53707458, 0.41846987],
       [0.6871369 , 0.7068723 , 0.20881475]])

In [34]:
# Psuedo-random numbers
np.random.seed()